# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
- repo: https://github.com/psf/black
  rev: 23.12.0
  hooks:
  - id: black
    language_version: python3.10

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.7.1'
  hooks:
  - id: mypy
    additional_dependencies: [types-requests==2.31.0, jax==0.4.23, jaxlib==0.4.19, ml_dtypes==0.2.0, numpy==1.26.0, scipy==1.11.2, torch==2.1.0, torchvision==0.16.0, absl-py==2.0.0]
    args: [--config=pyproject.toml]